
server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/regdbapi1
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Registration-api
